name: Maven Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      path-file-all:
        description: 'Ruta del archivo'
        required: false
        default: '/GRCHDSW1/swgrvone/reception/GVT_001234-D241118-H183623-ALL.chg'

jobs:
  test:
    runs-on: ubuntu-latest

    outputs:
      path-file-all: ${{ steps.show-info.outputs.path-file-all }}
      run-number: ${{ steps.show-info.outputs.run-number }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Run Maven tests
      run: mvn test

    - name: Debug Inputs
      run: |
        echo "Inputs disponibles:"
        echo "${{ toJson(github.event.inputs) }}"

    - name: Show inputs and context
      id: show-info
      run: |
        echo "Path File All: ${{ github.event.inputs.path-file-all }}"
        echo "path-file-all=${{ github.event.inputs.path-file-all }}" >> $GITHUB_ENV
        echo "run-number=${{ github.run_number }}" >> $GITHUB_ENV
      env:
        path-file-all: ${{ github.event.inputs.path-file-all }}
        run-number: ${{ github.run_number }}
      outputs:
        path-file-all: ${{ env.path-file-all }}
        run-number: ${{ env.run-number }}

    - name: Output summary
      run: |
        echo "Resumen del Workflow:"
        echo "Ruta del archivo: ${{ steps.show-info.outputs.path-file-all }}"
        echo "Número de ejecución: ${{ steps.show-info.outputs.run-number }}"
